name: "01-building-blocks"
on:  push

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Hello World"
        run: echo "Hello World"

  echo-goodbye-world:
    runs-on: ubuntu-latest
    steps:
      - name: "Failed step"
        run: |
          echo "I will failam"
          echo "a multi-line"
          echo "script"
      - name: "Echo Goodbye World"
        run: echo "Goodbye World"