name: 02 - Workflow Events
on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "Show the triggering event"
        run: echo "Event name ${{ github.event_name }}"